[package]
name = "otp"
edition = "2021"
version = "2.0.0"
license = "MIT License"
authors = ["Steven Ortiz"]

[lib]
doc = false

[[bin]]
name = "otp"
doc = false

[dependencies]
rand = "0.8.5"
structopt = { version = "0.3.26", default-features = false }
