[package]
name = "otp"
edition = "2018"
version = "2.0.0"
license = "MIT License"
authors = ["Steven Ortiz"]

[lib]
doc = false

[[bin]]
name = "otp"
doc = false

[dependencies]
rand = "0.7.2"
structopt = { version = "0.3.4", default-features = false }
