[package]
name = "otp"
edition = "2024"
version = "3.0.0"
license = "MIT License"
authors = ["Steven Ortiz"]

[lib]
doc = false

[[bin]]
name = "otp"
doc = false

[dependencies]
rand = "0.9.0"
clap = { version = "4.5.32", features = ["derive"] }
